/* eslint max-len: 0 */

import {DataItem} from '../../../../../../src/common/types/plugins/modules';

const deployment: DataItem = {
  category: 'Deployment',
  items: [
    {
      name: 'HTTP_PROXY',
      type: 'Input',
      description:
        'A URL to proxy unencrypted HTTP requests through. When set, n8n proxies all unencrypted HTTP traffic from nodes through the proxy URL.',
    },
    {
      name: 'HTTPS_PROXY',
      type: 'Input',
      description:
        'A URL to proxy TLS/SSL encrypted HTTP requests through. When set, n8n proxies all TLS/SSL encrypted HTTP traffic from nodes through the proxy URL.',
    },
    {
      name: 'ALL_PROXY',
      type: 'Input',
      description:
        "A URL to proxy both unencrypted and encrypted HTTP requests through. When set, n8n uses this value when more specific variables (`HTTP_PROXY` or `HTTPS_PROXY`) aren't present.",
    },
    {
      name: 'NO_PROXY',
      type: 'Input',
      description:
        'A comma-separated list of hostnames or URLs that should bypass the proxy. When using `HTTP_PROXY`, `HTTPS_PROXY`, or `ALL_PROXY`, n8n will connect directly to the URLs or hostnames defined here instead of using the proxy.',
    },
    {
      name: 'N8N_EDITOR_BASE_URL',
      type: 'Input',
      description:
        'Public URL where users can access the editor. Also used for emails sent from n8n and the redirect URL for SAML based authentication.',
    },
    {
      name: 'N8N_CONFIG_FILES',
      type: 'Input',
      description: 'Use to provide the path to any JSON configuration file.',
    },
    {name: 'N8N_DISABLE_UI', type: 'CheckBox', description: 'Set to `true` to disable the UI.'},
    {name: 'N8N_PREVIEW_MODE', type: 'CheckBox', description: 'Set to `true` to run in preview mode.'},
    {
      name: 'N8N_TEMPLATES_ENABLED',
      type: 'CheckBox',
      defaultValue: false,
      description: 'Enables workflow templates (true) or disable (false).',
    },
    {
      name: 'N8N_TEMPLATES_HOST',
      type: 'Input',
      defaultValue: 'https://api.n8n.io',
      description:
        "Change this if creating your own workflow template library. Note that to use your own workflow templates library, your API must provide the same endpoints and response structure as n8n's. Refer to Workflow templates for more information.",
    },
    {
      name: 'N8N_ENCRYPTION_KEY',
      type: 'Input',
      defaultValue: 'Random key generated by n8n',
      description:
        'Provide a custom key used to encrypt credentials in the n8n database. By default n8n generates a random key on first launch.',
    },
    {
      name: 'N8N_USER_FOLDER',
      type: 'Input',
      defaultValue: 'user-folder',
      description:
        'Provide the path where n8n will create the .n8n folder. This directory stores user-specific data, such as database file and encryption key.',
    },
    {name: 'N8N_PATH', type: 'Input', defaultValue: '/', description: 'The path n8n deploys to.'},
    {name: 'N8N_HOST', type: 'Input', defaultValue: 'localhost', description: 'Host name n8n runs on.'},
    {name: 'N8N_PORT', type: 'Input', defaultValue: 5678, description: 'The HTTP port n8n runs on.'},
    {
      name: 'N8N_LISTEN_ADDRESS',
      type: 'Input',
      defaultValue: '::',
      description: 'The IP address n8n should listen on.',
    },
    {
      name: 'N8N_PROTOCOL',
      type: 'DropDown',
      defaultValue: 'http',
      values: ['http', 'https'],
      description: 'The protocol used to reach n8n.',
    },
    {name: 'N8N_SSL_KEY', type: 'Input', description: 'The SSL key for HTTPS protocol.'},
    {name: 'N8N_SSL_CERT', type: 'Input', description: 'The SSL certificate for HTTPS protocol.'},
    {
      name: 'N8N_PERSONALIZATION_ENABLED',
      type: 'CheckBox',
      description: 'Whether to ask users personalisation questions and then customise n8n accordingly.',
    },
    {
      name: 'N8N_VERSION_NOTIFICATIONS_ENABLED',
      type: 'CheckBox',
      description: 'When enabled, n8n sends notifications of new versions and security updates.',
    },
    {
      name: 'N8N_VERSION_NOTIFICATIONS_ENDPOINT',
      type: 'Input',
      defaultValue: 'https://api.n8n.io/versions/',
      description: 'The endpoint to retrieve where version information.',
    },
    {
      name: 'N8N_VERSION_NOTIFICATIONS_INFO_URL',
      type: 'Input',
      defaultValue: 'https://docs.n8n.io/getting-started/installation/updating.html',
      description: 'The URL displayed in the New Versions panel for more information.',
    },
    {
      name: 'N8N_DIAGNOSTICS_ENABLED',
      type: 'CheckBox',
      description:
        "Whether to share selected, anonymous telemetry with n8n. Note that if you set this to `false`, you can't enable Ask AI in the Code node.",
    },
    {
      name: 'N8N_DIAGNOSTICS_CONFIG_FRONTEND',
      type: 'Input',
      defaultValue: '1zPn9bgWPzlQc0p8Gj1uiK6DOTn;https://telemetry.n8n.io',
      description: 'Telemetry configuration for the frontend.',
    },
    {
      name: 'N8N_DIAGNOSTICS_CONFIG_BACKEND',
      type: 'Input',
      defaultValue: '1zPn7YoGC3ZXE9zLeTKLuQCB4F6;https://telemetry.n8n.io/v1/batch',
      description: 'Telemetry configuration for the backend.',
    },
    {
      name: 'N8N_PUSH_BACKEND',
      type: 'Input',
      defaultValue: 'websocket',
      description:
        'Choose whether the n8n backend uses server-sent events (`sse`) or WebSockets (`websocket`) to send changes to the UI.',
    },
    {
      name: 'VUE_APP_URL_BASE_API',
      type: 'Input',
      defaultValue: 'http://localhost:5678/',
      description:
        'Used when building the n8n-editor-ui package manually to set how the frontend can reach the backend API. Refer to Configure the Base URL.',
    },
    {
      name: 'N8N_HIRING_BANNER_ENABLED',
      type: 'CheckBox',
      description: 'Whether to show the n8n hiring banner in the console (true) or not (false).',
    },
    {
      name: 'N8N_PUBLIC_API_SWAGGERUI_DISABLED',
      type: 'CheckBox',
      description: 'Whether the Swagger UI (API playground) is disabled (true) or not (false).',
    },
    {
      name: 'N8N_PUBLIC_API_DISABLED',
      type: 'CheckBox',
      description: 'Whether to disable the public API (true) or not (false).',
    },
    {
      name: 'N8N_PUBLIC_API_ENDPOINT',
      type: 'Input',
      defaultValue: 'api',
      description: 'Path for the public API endpoints.',
    },
    {
      name: 'N8N_GRACEFUL_SHUTDOWN_TIMEOUT',
      type: 'Input',
      defaultValue: 30,
      description:
        'How long should the n8n process wait (in seconds) for components to shut down before exiting the process.',
    },
    {
      name: 'N8N_DEV_RELOAD',
      type: 'CheckBox',
      description:
        'When working on the n8n source code, set this to `true` to automatically reload or restart the application when changes occur in the source code files.',
    },
    {
      name: 'N8N_REINSTALL_MISSING_PACKAGES',
      type: 'CheckBox',
      description: 'If set to `true`, n8n will automatically attempt to reinstall any missing packages.',
    },
    {
      name: 'N8N_TUNNEL_SUBDOMAIN',
      type: 'Input',
      description: 'Specifies the subdomain for the n8n tunnel. If not set, n8n generates a random subdomain.',
    },
    {
      name: 'N8N_PROXY_HOPS',
      type: 'Input',
      defaultValue: 0,
      description: 'Number of reverse-proxies n8n is running behind.',
    },
  ],
};

export default deployment;
